#+title: My personal utils

Small housekeeping utilities.

A few tricks and personal rules for Bash are available in these [[file:bash_notes.org][notes]].

I "install" these scripts with [[https://github.com/casey/just][Just]]:

#+begin_src bash
  just install-symlinks
#+end_src

This Just recipe will symlink all scripts to =~/bin=, stripping their
extension.

* Documentation
:PROPERTIES:
:CREATED:  [2026-03-27 Fri 10:41]
:END:

** =sbx.bash=
:PROPERTIES:
:CREATED:  [2026-03-27 Fri 10:40]
:END:

⚠️ This is a work in progress.

=sbx= is a script that creates a [[https://github.com/containers/bubblewrap][bubblewrap]] (=bwrap=) sandbox using
preconfigured homedirs.

Take a look at it: [[file:sbx.bash][sbx.bash]].

- =--sandbox= uses a particular sandbox homedir.
- =--project= binds a particular project in the sandbox home.

The homedirs live under =~/etc/sandboxes=. The entire directory is
under version control (very privately, of course). A typical sandbox
homedir could look like this:

#+begin_example
  codex
  ├── etc
  │   ├── group
  │   ├── nsswitch.conf
  │   └── passwd
  ├── home
  │   ├── .codex
  │   │   ├── auth.json
  │   │   └── config.toml
  │   └── .ssh
  │       ├── id_ed25519
  │       ├── id_ed25519.pub
  │       ├── known_hosts
  │       └── known_hosts.old
  └── .sbx-profile
#+end_example

- =home= is what will become the actual =$HOME= in the bwrap sandbox.
- =.sbx-profile= defines extra arguments for =bwrap=. For codex:

  #+begin_src sh
    BWRAP_EXTRA+=(
      --ro-bind "${HOME}/.local/share/fnm" "${BWRAP_HOME}/.local/share/fnm"
      --setenv PATH "${BWRAP_HOME}/.local/share/fnm/node-versions/v24.13.0/installation/bin:/usr/bin:/bin"
    )
  #+end_src
